---
extends:
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
plugins:
  - "react"
parserOptions:
  project: ./tsconfig.eslint.json
rules:
  "@typescript-eslint/no-confusing-void-expression": off
  func-style: off
  sort-imports: off
  operator-linebreak: off
